# Generated by Django 5.2.4 on 2025-07-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-date', 'movie', 'author'), 'verbose_name': 'Critique', 'verbose_name_plural': 'Critiques'},
        ),
    ]
