# Generated by Django 5.2.4 on 2025-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('lastname', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Réalisateur/trice',
                'verbose_name_plural': 'Réalisateur/trice(s)',
                'ordering': ('lastname', 'forename'),
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('synopsys', models.TextField(verbose_name='Synopsys')),
                ('duration', models.IntegerField(verbose_name='Durée (en minutes)')),
                ('release_date', models.DateField(verbose_name='Date de sortie en France')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Image')),
                ('country_of_production', models.ManyToManyField(to='movies.country', verbose_name='Pays de production')),
                ('direction', models.ManyToManyField(to='movies.director', verbose_name='Réalisateur/trice(s)')),
                ('gender', models.ManyToManyField(to='movies.gender', verbose_name='Genre(s)')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ('title', '-release_date'),
            },
        ),
    ]
