# Generated by Django 5.2.4 on 2025-07-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title', '-release_year'), 'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de sortie en France'),
        ),
    ]
