# Generated by Django 5.2.4 on 2025-07-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='synopsys',
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée (en minutes)'),
        ),
    ]
