# Generated by Django 5.2.4 on 2025-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_synopsys_movie_synopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country_of_production',
            field=models.ManyToManyField(blank=True, to='movies.country', verbose_name='Pays de production'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='direction',
            field=models.ManyToManyField(blank=True, to='movies.director', verbose_name='Réalisateur/trice(s)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.ManyToManyField(blank=True, to='movies.gender', verbose_name='Genre(s)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titre'),
        ),
    ]
